"""Add store coordinates columns

Revision ID: 001_add_store_coordinates
Revises: 
Create Date: 2026-05-06 22:08:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '001_add_store_coordinates'
down_revision = None
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table"""
    bind = op.get_context().bind
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('stores', 'latitude'):
        op.add_column('stores', sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True))
    if not column_exists('stores', 'longitude'):
        op.add_column('stores', sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'longitude')
    op.drop_column('stores', 'latitude')
    # ### end Alembic commands ###
