"""Create distance cache table

Revision ID: 002_create_distance_cache
Revises: 001_add_store_coordinates
Create Date: 2026-05-06 22:08:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '002_create_distance_cache'
down_revision = '001_add_store_coordinates'
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists"""
    bind = op.get_context().bind
    inspector = inspect(bind)
    tables = inspector.get_table_names()
    return table_name in tables


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if table_exists('distance_cache'):
        return
    op.create_table('distance_cache',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('origin_lat', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('origin_lng', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('dest_lat', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('dest_lng', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distance_cache_created_at'), 'distance_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_distance_cache_dest_coords'), 'distance_cache', ['dest_lat', 'dest_lng'], unique=False)
    op.create_index(op.f('ix_distance_cache_origin_coords'), 'distance_cache', ['origin_lat', 'origin_lng'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_distance_cache_origin_coords'), table_name='distance_cache')
    op.drop_index(op.f('ix_distance_cache_dest_coords'), table_name='distance_cache')
    op.drop_index(op.f('ix_distance_cache_created_at'), table_name='distance_cache')
    op.drop_table('distance_cache')
    # ### end Alembic commands ###
