"""empty message

Revision ID: 021585b592d5
Revises: 64489a8644ba
Create Date: 2025-12-08 18:20:41.433929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021585b592d5'
down_revision = '64489a8644ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # buyer_profiles table was already created during an earlier partial migration run,
    # so we only add the new user columns here to avoid duplicate table errors.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('given_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True))
        batch_op.add_column(sa.Column('surname', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True))
        batch_op.add_column(sa.Column('contact_number', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contact_number')
        batch_op.drop_column('surname')
        batch_op.drop_column('given_name')
    op.drop_table('buyer_profiles')
    # ### end Alembic commands ###
