"""empty message

Revision ID: 07f1910a5a9f
Revises: 45d59a828979
Create Date: 2025-12-11 09:53:52.357624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f1910a5a9f'
down_revision = '45d59a828979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 
    pass
    # with op.batch_alter_table('store_registrations', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('seller_id'))

    # with op.batch_alter_table('stores', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('seller_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('seller_id'), ['seller_id'], unique=True)

    with op.batch_alter_table('store_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('seller_id'), ['seller_id'], unique=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
