"""add rider deliveries

Revision ID: 193d70db8d79
Revises: 2da0b6927737
Create Date: 2025-12-11 17:17:38.748040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193d70db8d79'
down_revision = '2da0b6927737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rider_deliveries',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PICKUP', 'TRANSIT', 'DELIVERED', 'CANCELLED', name='deliverystatus'), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('rider_id', sa.BIGINT(), nullable=True),
    sa.Column('order_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rider_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rider_deliveries')
    # ### end Alembic commands ###
