"""empty message

Revision ID: 2fa744df91e5
Revises: <new_id>
Create Date: 2025-12-14 01:07:50.011407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa744df91e5'
down_revision = '<new_id>'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('notifications', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_notifications_user_role_page'))

    with op.batch_alter_table('rider_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proof_photo_path', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('proof_note', sa.TEXT(), nullable=True))

    # with op.batch_alter_table('store_registrations', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('seller_id'))

    # with op.batch_alter_table('stores', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('seller_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('stores', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('seller_id'), ['seller_id'], unique=True)

    # with op.batch_alter_table('store_registrations', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('seller_id'), ['seller_id'], unique=True)

    with op.batch_alter_table('rider_deliveries', schema=None) as batch_op:
        batch_op.drop_column('proof_note')
        batch_op.drop_column('proof_photo_path')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_role_page'), ['user_id', 'role', 'page'], unique=False)

    # ### end Alembic commands ###
