"""Add shop settings tables

Revision ID: 34a5b6d32064
Revises: 2fa744df91e5
Create Date: 2026-05-06 13:30:17.344370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a5b6d32064'
down_revision = '2fa744df91e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_settings',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('auto_reply_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_reply_message', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('store_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('order_settings',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('allow_cancellation', sa.Boolean(), nullable=False),
    sa.Column('max_cancellation_hours', sa.Integer(), nullable=False),
    sa.Column('allow_returns', sa.Boolean(), nullable=False),
    sa.Column('return_period_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('store_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('payment_settings',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('cod_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('store_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('shipping_settings',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('region_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('region_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('province_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('province_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('city_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('city_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('shipping_fee', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('store_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_customization',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('announcement', sa.TEXT(), nullable=True),
    sa.Column('primary_color', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('theme_mode', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('store_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_customization')
    op.drop_table('shipping_settings')
    op.drop_table('payment_settings')
    op.drop_table('order_settings')
    op.drop_table('chat_settings')
    # ### end Alembic commands ###
