"""empty message

Revision ID: 4269324a07c9
Revises: f28fa5e4f611
Create Date: 2025-12-11 12:02:25.748278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4269324a07c9'
down_revision = 'f28fa5e4f611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('product_variations',
    # sa.Column('id', sa.BIGINT(), nullable=False),
    # sa.Column('product_id', sa.BIGINT(), nullable=False),
    # sa.Column('size', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    # sa.Column('color', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    # sa.Column('sku', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    # sa.Column('inventory', sa.Integer(), nullable=False),
    # sa.Column('price', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('products', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('rating', sa.Float(), nullable=False))
    #     batch_op.add_column(sa.Column('review_count', sa.Integer(), nullable=False))

    # with op.batch_alter_table('store_registrations', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('seller_id'))

    # with op.batch_alter_table('stores', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('seller_id'))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('seller_id'), ['seller_id'], unique=True)

    with op.batch_alter_table('store_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('seller_id'), ['seller_id'], unique=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('review_count')
        batch_op.drop_column('rating')

    op.drop_table('product_variations')
    # ### end Alembic commands ###
