"""empty message

Revision ID: 45d59a828979
Revises: cf6564734b84
Create Date: 2025-12-11 09:25:08.634388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d59a828979'
down_revision = 'cf6564734b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'RETURNED', name='orderstatus'), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('shipping_address', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('buyer_id', sa.BIGINT(), nullable=True),
    sa.Column('store_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('order_id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('variation', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # with op.batch_alter_table('store_registrations', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('seller_id'))

    # with op.batch_alter_table('stores', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('seller_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('stores', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('seller_id'), ['seller_id'], unique=True)

    # with op.batch_alter_table('store_registrations', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('seller_id'), ['seller_id'], unique=True)

    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
