"""Changes product.seller_id to store_id fk

Revision ID: 621ccc25ff5a
Revises: ed23d17dd682
Create Date: 2025-10-24 12:53:21.763513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '621ccc25ff5a'
down_revision = 'ed23d17dd682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.BIGINT(), nullable=False))
        batch_op.drop_constraint(batch_op.f('products_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'stores', ['store_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('products_ibfk_1'), 'seller_profiles', ['seller_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('store_id')

    # ### end Alembic commands ###
