"""Readds unique indices to seller_profiles, stores, and store_registrations

Revision ID: 64489a8644ba
Revises: 6a0567ecc4c3
Create Date: 2025-10-29 13:48:11.851434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64489a8644ba'
down_revision = '6a0567ecc4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
