"""Removes indices

Revision ID: 6a0567ecc4c3
Revises: 621ccc25ff5a
Create Date: 2025-10-29 13:40:35.227855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0567ecc4c3'
down_revision = '621ccc25ff5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('seller_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###
