"""Initial migration

Revision ID: 6fc0c5b0549d
Revises: 
Create Date: 2026-05-27 13:14:07.410254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc0c5b0549d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commission_settings',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('applies_to_product_price_only', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distance_cache',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('origin_lat', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('origin_lng', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('dest_lat', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('dest_lng', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_types',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('target_role', sa.String(length=20), nullable=False),
    sa.Column('type_key', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_types_target_role'), ['target_role'], unique=False)

    op.create_table('role',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('email', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('password_hash', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('username', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('given_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('surname', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('contact_number', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('buyer_profiles',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('region_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('region_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('province_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('province_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('municipality_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('municipality_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('barangay_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('barangay_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('street_address', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('postal_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('avatar_path', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('valid_id_path', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('carts',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('title', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('role', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('page', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_code',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_code_user_id'), ['user_id'], unique=False)

    op.create_table('rider_profiles',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('region_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('region_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('province_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('province_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('municipality_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('municipality_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('barangay_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('barangay_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('street_address', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('postal_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('vehicle_type', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('license_number', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('license_path', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('orcr_path', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('avatar_path', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('seller_profiles',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('full_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('residential_address', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('personal_phone_number', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('country', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('province', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('city', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('region_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('region_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('province_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('province_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('municipality_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('municipality_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('barangay_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('barangay_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('street_address', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('postal_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('avatar_path', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('banner_path', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('valid_id_path', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_addresses',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('street_address', sa.String(length=500), nullable=False),
    sa.Column('barangay_name', sa.String(length=100), nullable=True),
    sa.Column('municipality_name', sa.String(length=100), nullable=False),
    sa.Column('province_name', sa.String(length=100), nullable=False),
    sa.Column('region_name', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('region_code', sa.String(length=20), nullable=True),
    sa.Column('province_code', sa.String(length=20), nullable=True),
    sa.Column('municipality_code', sa.String(length=20), nullable=True),
    sa.Column('barangay_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_presence',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('role_id', sa.BIGINT(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('seller_wallets',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('seller_id', sa.BIGINT(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id')
    )
    op.create_table('store_registrations',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('seller_id', sa.BIGINT(), nullable=True),
    sa.Column('request_status', sa.Enum('ACCEPTED', 'REJECTED', 'PENDING', name='storerequeststatus'), nullable=False),
    sa.Column('store_purpose', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('shop_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('tagline', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('categories_json', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('dti_path', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('bir_tin_path', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('business_permit_path', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('seller_id', sa.BIGINT(), nullable=False),
    sa.Column('store_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('store_email', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('country', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('address', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('store_phone_number', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id'),
    sa.UniqueConstraint('store_name'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('chat_settings',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('auto_reply_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_reply_message', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('store_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('coupons',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('min_order_amount', sa.Float(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('store_id', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'store_id', name='uq_coupon_code_store')
    )
    op.create_table('order_settings',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('allow_cancellation', sa.Boolean(), nullable=False),
    sa.Column('max_cancellation_hours', sa.Integer(), nullable=False),
    sa.Column('allow_returns', sa.Boolean(), nullable=False),
    sa.Column('return_period_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('store_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('payment_settings',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('cod_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('store_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('products',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('store_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('moderation_status', sa.Enum('ACTIVE', 'UNDER_REVIEW', 'HIDDEN', 'REMOVED', 'RESTRICTED', name='productmoderationstatus'), nullable=False),
    sa.Column('moderation_reason', sa.TEXT(), nullable=True),
    sa.Column('moderation_updated_at', sa.DateTime(), nullable=True),
    sa.Column('moderation_updated_by', sa.BIGINT(), nullable=True),
    sa.Column('edit_requested_at', sa.DateTime(), nullable=True),
    sa.Column('edit_request_note', sa.TEXT(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('tags_json', sa.TEXT(), nullable=True),
    sa.Column('product_condition', sa.String(length=50), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('size_chart_json', sa.TEXT(), nullable=True),
    sa.Column('care_instructions', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['moderation_updated_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipping_settings',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('region_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('region_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('province_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('province_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('city_code', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('city_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('shipping_fee', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('store_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_customization',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('announcement', sa.TEXT(), nullable=True),
    sa.Column('primary_color', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('theme_mode', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('store_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('store_follows',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('store_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'RETURNED', 'COMPLETED', name='orderstatus'), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('shipping_fee', sa.Float(), nullable=False),
    sa.Column('admin_commission', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('shipping_address', sa.TEXT(), nullable=True),
    sa.Column('delivery_notes', sa.TEXT(), nullable=True),
    sa.Column('coupon_id', sa.BIGINT(), nullable=True),
    sa.Column('coupon_discount', sa.Float(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('buyer_id', sa.BIGINT(), nullable=True),
    sa.Column('store_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('product_categories',
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('category_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'category_id')
    )
    op.create_table('product_media',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_moderation_logs',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('admin_id', sa.BIGINT(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variations',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('size', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('color', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('sku', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('inventory', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recently_viewed_products',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlist_items',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('cart_id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('variation_id', sa.BIGINT(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_add', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variation_id'], ['product_variations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('kind', sa.Enum('BUYER_SELLER', 'SELLER_ADMIN', 'ADMIN_BUYER', 'RIDER_SELLER', name='conversationkind'), nullable=False),
    sa.Column('store_id', sa.BIGINT(), nullable=True),
    sa.Column('order_id', sa.BIGINT(), nullable=True),
    sa.Column('buyer_user_id', sa.BIGINT(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_preview', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupon_redemptions',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('coupon_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('order_id', sa.BIGINT(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('order_id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('variation', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_transactions',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('HELD', 'SETTLED', 'REFUNDED', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.BIGINT(), nullable=False),
    sa.Column('seller_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem_reports',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('reporter_user_id', sa.BIGINT(), nullable=False),
    sa.Column('reporter_role', sa.String(length=20), nullable=False),
    sa.Column('report_type_id', sa.BIGINT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'INVESTIGATING', 'RESOLVED', 'DISMISSED', name='reportstatus'), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('target_user_id', sa.BIGINT(), nullable=True),
    sa.Column('target_role', sa.String(length=20), nullable=True),
    sa.Column('store_id', sa.BIGINT(), nullable=True),
    sa.Column('order_id', sa.BIGINT(), nullable=True),
    sa.Column('admin_notes', sa.TEXT(), nullable=True),
    sa.Column('resolved_by', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_type_id'], ['report_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rider_deliveries',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('order_id', sa.BIGINT(), nullable=True),
    sa.Column('rider_id', sa.BIGINT(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PICKUP', 'TRANSIT', 'DELIVERED', 'CANCELLED', name='deliverystatus'), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('proof_photo_path', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=True),
    sa.Column('proof_note', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rider_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('conversation_id', sa.BIGINT(), nullable=False),
    sa.Column('sender_user_id', sa.BIGINT(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'IMAGE', 'FILE', 'PRODUCT', 'ORDER', 'SYSTEM', name='chatmessagetype'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_participants',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('conversation_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('participant_role', sa.String(length=32), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('punishments',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('report_id', sa.BIGINT(), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('severity', sa.Enum('WARNING', 'RESTRICTION', 'BAN', name='punishmentseverity'), nullable=False),
    sa.Column('restriction_type', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('issued_by', sa.BIGINT(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issued_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['problem_reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refund_requests',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED_BY_SELLER', 'REJECTED_BY_SELLER', 'APPROVED', 'REJECTED', 'DISPUTED', 'EVIDENCE_REQUESTED', 'ADMIN_REVIEW', name='refundstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.BIGINT(), nullable=False),
    sa.Column('buyer_id', sa.BIGINT(), nullable=True),
    sa.Column('seller_id', sa.BIGINT(), nullable=True),
    sa.Column('payment_transaction_id', sa.BIGINT(), nullable=True),
    sa.Column('buyer_evidence_note', sa.TEXT(), nullable=True),
    sa.Column('seller_response_note', sa.TEXT(), nullable=True),
    sa.Column('admin_note', sa.TEXT(), nullable=True),
    sa.Column('evidence_paths_json', sa.TEXT(), nullable=True),
    sa.Column('disputed_at', sa.DateTime(), nullable=True),
    sa.Column('evidence_requested_at', sa.DateTime(), nullable=True),
    sa.Column('frozen_at', sa.DateTime(), nullable=True),
    sa.Column('is_transaction_frozen', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_evidence',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('report_id', sa.BIGINT(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['problem_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_format', sa.String(length=32), nullable=False),
    sa.Column('ratings_json', sa.TEXT(), nullable=True),
    sa.Column('delivery_satisfaction', sa.Integer(), nullable=True),
    sa.Column('delivery_pills_json', sa.TEXT(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('images_json', sa.TEXT(), nullable=True),
    sa.Column('seller_reply', sa.TEXT(), nullable=True),
    sa.Column('seller_reply_at', sa.DateTime(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('order_item_id', sa.BIGINT(), nullable=False),
    sa.Column('buyer_id', sa.BIGINT(), nullable=True),
    sa.Column('product_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id')
    )
    op.create_table('rider_earnings',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('delivery_id', sa.BIGINT(), nullable=False),
    sa.Column('rider_id', sa.BIGINT(), nullable=False),
    sa.Column('shipping_fee_total', sa.Float(), nullable=False),
    sa.Column('rider_share_percentage', sa.Float(), nullable=False),
    sa.Column('admin_share_percentage', sa.Float(), nullable=False),
    sa.Column('seller_share_percentage', sa.Float(), nullable=False),
    sa.Column('rider_earnings', sa.Float(), nullable=False),
    sa.Column('admin_earnings', sa.Float(), nullable=False),
    sa.Column('seller_earnings', sa.Float(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_id'], ['rider_deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rider_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violation_history',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('report_id', sa.BIGINT(), nullable=True),
    sa.Column('punishment_id', sa.BIGINT(), nullable=True),
    sa.Column('violation_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('issued_by', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issued_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['punishment_id'], ['punishments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['problem_reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violation_history')
    op.drop_table('rider_earnings')
    op.drop_table('reviews')
    op.drop_table('report_evidence')
    op.drop_table('refund_requests')
    op.drop_table('punishments')
    op.drop_table('conversation_participants')
    op.drop_table('chat_messages')
    op.drop_table('rider_deliveries')
    op.drop_table('problem_reports')
    op.drop_table('payment_transactions')
    op.drop_table('order_items')
    op.drop_table('coupon_redemptions')
    op.drop_table('conversations')
    op.drop_table('cart_items')
    op.drop_table('wishlist_items')
    op.drop_table('recently_viewed_products')
    op.drop_table('product_variations')
    op.drop_table('product_moderation_logs')
    op.drop_table('product_media')
    op.drop_table('product_categories')
    op.drop_table('orders')
    op.drop_table('store_follows')
    op.drop_table('shop_customization')
    op.drop_table('shipping_settings')
    op.drop_table('products')
    op.drop_table('payment_settings')
    op.drop_table('order_settings')
    op.drop_table('coupons')
    op.drop_table('chat_settings')
    op.drop_table('stores')
    op.drop_table('store_registrations')
    op.drop_table('seller_wallets')
    op.drop_table('user_roles')
    op.drop_table('user_presence')
    op.drop_table('user_addresses')
    op.drop_table('seller_profiles')
    op.drop_table('rider_profiles')
    with op.batch_alter_table('password_reset_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_code_user_id'))

    op.drop_table('password_reset_code')
    op.drop_table('notifications')
    op.drop_table('carts')
    op.drop_table('buyer_profiles')
    op.drop_table('user')
    op.drop_table('role')
    with op.batch_alter_table('report_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_types_target_role'))

    op.drop_table('report_types')
    op.drop_table('distance_cache')
    op.drop_table('commission_settings')
    op.drop_table('categories')
    # ### end Alembic commands ###
