"""add refund_requests table

Revision ID: 7b12585dcf4b
Revises: abcd1234abcd
Create Date: 2025-12-12 08:47:24.531920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b12585dcf4b'
down_revision = 'abcd1234abcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The refund_requests table already exists in the database (it was
    # created on a previous migration attempt), so this upgrade does not
    # need to apply any DDL. It simply records the revision.
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refund_requests')
    # ### end Alembic commands ###
