"""Alters store_registrations.request_status col type from str to enum

Revision ID: 7d9965f5df43
Revises: db4976136a6f
Create Date: 2025-10-23 20:15:55.586026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d9965f5df43'
down_revision = 'db4976136a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_registrations', schema=None) as batch_op:
        batch_op.alter_column('request_status',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('ACCEPTED', 'REJECTED', 'PENDING', name='storerequeststatus'),
               existing_nullable=False,
               postgresql_using='request_status::storerequeststatus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_registrations', schema=None) as batch_op:
        batch_op.alter_column('request_status',
               existing_type=sa.Enum('ACCEPTED', 'REJECTED', 'PENDING', name='storerequeststatus'),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False,
               postgresql_using='request_status::text')

    # ### end Alembic commands ###
