"""Adds store model

Revision ID: 8c6e59835518
Revises: 9100595e97a0
Create Date: 2025-10-24 12:50:34.870773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6e59835518'
down_revision = '9100595e97a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('store_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('store_email', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('country', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('address', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('store_phone_number', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stores')
    # ### end Alembic commands ###
