"""Removes store_registrations.is_accepted col

Revision ID: 9f65ec0c8ea8
Revises: 2f87eb08bddb
Create Date: 2025-10-19 12:25:58.949825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f65ec0c8ea8'
down_revision = '2f87eb08bddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_registrations',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('request_status', sa.Enum('ACCEPTED', 'REJECTED', 'PENDING', name='storerequeststatus'), nullable=False),
    sa.Column('store_purpose', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('seller_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seller_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_registrations')
    # ### end Alembic commands ###
