"""empty message

Revision ID: bf4d44f6b277
Revises: 8fd9bb783382
Create Date: 2025-12-11 20:08:41.694254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4d44f6b277'
down_revision = '8fd9bb783382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Both seller_wallets and payment_transactions already exist in the
    # database, so this migration does not need to apply any schema
    # changes on upgrade. It simply records the revision.
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_transactions')
    op.drop_table('seller_wallets')
    # ### end Alembic commands ###
