"""Initial migration

Revision ID: d51e64342736
Revises: 
Create Date: 2025-10-19 10:43:39.768237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51e64342736'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('email', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('password_hash', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('username', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('seller_profiles',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('full_name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('residential_address', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('personal_phone_number', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('country', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('province', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('city', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('role_id', sa.BIGINT(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('products',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('seller_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_categories',
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('category_id', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_categories')
    op.drop_table('products')
    op.drop_table('user_roles')
    op.drop_table('seller_profiles')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('categories')
    # ### end Alembic commands ###
