"""Adds stores.seller_id fk

Revision ID: ed23d17dd682
Revises: 8c6e59835518
Create Date: 2025-10-24 12:52:06.281590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed23d17dd682'
down_revision = '8c6e59835518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.BIGINT(), nullable=False))
        batch_op.create_unique_constraint(None, ['seller_id'])
        batch_op.create_foreign_key(None, 'seller_profiles', ['seller_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###
