"""empty message

Revision ID: f28fa5e4f611
Revises: 07f1910a5a9f
Create Date: 2025-12-11 11:23:16.329570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28fa5e4f611'
down_revision = '07f1910a5a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('product_media',
    # sa.Column('id', sa.BIGINT(), nullable=False),
    # sa.Column('product_id', sa.BIGINT(), nullable=False),
    # sa.Column('media_type', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    # sa.Column('path', sa.String().with_variant(sa.VARCHAR(length=255), 'mysql'), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('store_registrations', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('seller_id'))

    # with op.batch_alter_table('stores', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('seller_id'))
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('seller_id'), ['seller_id'], unique=True)

    with op.batch_alter_table('store_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('seller_id'), ['seller_id'], unique=True)

    op.drop_table('product_media')
    # ### end Alembic commands ###
