import type { Product, DashboardOverview, SalesData, CategoryPerformance } from "@/lib/types"

// Mock Products
export const mockProducts: Product[] = [
  {
    id: "1",
    slug: "elegant-summer-dress",
    name: "Elegant Summer Dress",
    category: "dress-skirts",
    subcategory: "summer-dresses",
    description:
      "A beautiful flowing summer dress perfect for warm weather occasions. Made with breathable fabric and featuring a flattering A-line silhouette.",
    images: ["/elegant-summer-dress-pink.jpg", "/elegant-summer-dress-back-view.jpg"],
    variations: [
      { id: "v1", size: "S", color: "Blush Pink", colorHex: "#F4C9D6", sku: "ESD-S-BP", inventory: 15, price: 1299 },
      { id: "v2", size: "M", color: "Blush Pink", colorHex: "#F4C9D6", sku: "ESD-M-BP", inventory: 20, price: 1299 },
      { id: "v3", size: "L", color: "Blush Pink", colorHex: "#F4C9D6", sku: "ESD-L-BP", inventory: 12, price: 1299 },
      { id: "v4", size: "S", color: "Navy", colorHex: "#1E2A3A", sku: "ESD-S-NV", inventory: 10, price: 1299 },
      { id: "v5", size: "M", color: "Navy", colorHex: "#1E2A3A", sku: "ESD-M-NV", inventory: 18, price: 1299 },
    ],
    price: 1499,
    salePrice: 1299,
    rating: 4.8,
    reviewCount: 124,
    sellerId: "seller1",
    sellerName: "Pink Boutique",
    sellerLogo: "/elegant-boutique-logo.png",
    visibility: true,
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-20T00:00:00Z",
  },
  {
    id: "2",
    slug: "premium-yoga-leggings",
    name: "Premium Yoga Leggings",
    category: "activewear",
    subcategory: "yoga-pants",
    description:
      "High-waisted yoga leggings with four-way stretch fabric. Features moisture-wicking technology and a hidden pocket.",
    images: ["/yoga-leggings-black.jpg", "/yoga-leggings-side-view.jpg"],
    variations: [
      { id: "v6", size: "XS", color: "Black", colorHex: "#2E2E2E", sku: "PYL-XS-BK", inventory: 25, price: 899 },
      { id: "v7", size: "S", color: "Black", colorHex: "#2E2E2E", sku: "PYL-S-BK", inventory: 30, price: 899 },
      { id: "v8", size: "M", color: "Black", colorHex: "#2E2E2E", sku: "PYL-M-BK", inventory: 28, price: 899 },
      { id: "v9", size: "L", color: "Black", colorHex: "#2E2E2E", sku: "PYL-L-BK", inventory: 22, price: 899 },
    ],
    price: 999,
    salePrice: 899,
    rating: 4.9,
    reviewCount: 256,
    sellerId: "seller2",
    sellerName: "ActiveWear Hub",
    visibility: true,
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-01-18T00:00:00Z",
  },
  {
    id: "3",
    slug: "silk-blouse-collection",
    name: "Silk Blouse Collection",
    category: "tops-blouses",
    description: "Luxurious silk blouse with elegant draping. Perfect for office wear or evening occasions.",
    images: ["/silk-blouse-white-elegant.jpg"],
    variations: [
      { id: "v10", size: "S", color: "Ivory", colorHex: "#FAF7F9", sku: "SBC-S-IV", inventory: 8, price: 1899 },
      { id: "v11", size: "M", color: "Ivory", colorHex: "#FAF7F9", sku: "SBC-M-IV", inventory: 12, price: 1899 },
      { id: "v12", size: "L", color: "Ivory", colorHex: "#FAF7F9", sku: "SBC-L-IV", inventory: 6, price: 1899 },
    ],
    price: 1899,
    rating: 4.7,
    reviewCount: 89,
    sellerId: "seller1",
    sellerName: "Pink Boutique",
    visibility: true,
    createdAt: "2024-01-05T00:00:00Z",
    updatedAt: "2024-01-05T00:00:00Z",
  },
  {
    id: "4",
    slug: "cozy-winter-jacket",
    name: "Cozy Winter Jacket",
    category: "jackets-coats",
    description: "Warm and stylish winter jacket with faux fur lining. Water-resistant exterior.",
    images: ["/winter-jacket-women-beige.jpg"],
    variations: [
      { id: "v13", size: "S", color: "Beige", colorHex: "#F3E7DD", sku: "CWJ-S-BG", inventory: 10, price: 2499 },
      { id: "v14", size: "M", color: "Beige", colorHex: "#F3E7DD", sku: "CWJ-M-BG", inventory: 15, price: 2499 },
      { id: "v15", size: "L", color: "Beige", colorHex: "#F3E7DD", sku: "CWJ-L-BG", inventory: 8, price: 2499 },
    ],
    price: 2799,
    salePrice: 2499,
    rating: 4.6,
    reviewCount: 67,
    sellerId: "seller3",
    sellerName: "Winter Wardrobe",
    visibility: true,
    createdAt: "2024-01-08T00:00:00Z",
    updatedAt: "2024-01-12T00:00:00Z",
  },
  {
    id: "5",
    slug: "lace-lingerie-set",
    name: "Lace Lingerie Set",
    category: "lingerie-sleepwear",
    description: "Delicate lace lingerie set with matching bra and panty. Comfortable and elegant.",
    images: ["/lace-lingerie-set-pink.jpg"],
    variations: [
      { id: "v16", size: "S", color: "Rose", colorHex: "#C97A8C", sku: "LLS-S-RS", inventory: 20, price: 799 },
      { id: "v17", size: "M", color: "Rose", colorHex: "#C97A8C", sku: "LLS-M-RS", inventory: 25, price: 799 },
      { id: "v18", size: "L", color: "Rose", colorHex: "#C97A8C", sku: "LLS-L-RS", inventory: 18, price: 799 },
    ],
    price: 899,
    salePrice: 799,
    rating: 4.5,
    reviewCount: 145,
    sellerId: "seller4",
    sellerName: "Intimate Elegance",
    visibility: true,
    createdAt: "2024-01-12T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "6",
    slug: "statement-heels",
    name: "Statement Heels",
    category: "accessories-shoes",
    description: "Elegant statement heels perfect for special occasions. Features cushioned insole for comfort.",
    images: ["/statement-heels-women-pink.jpg"],
    variations: [
      { id: "v19", size: "36", color: "Blush", colorHex: "#F4C9D6", sku: "SH-36-BL", inventory: 8, price: 1599 },
      { id: "v20", size: "37", color: "Blush", colorHex: "#F4C9D6", sku: "SH-37-BL", inventory: 12, price: 1599 },
      { id: "v21", size: "38", color: "Blush", colorHex: "#F4C9D6", sku: "SH-38-BL", inventory: 10, price: 1599 },
      { id: "v22", size: "39", color: "Blush", colorHex: "#F4C9D6", sku: "SH-39-BL", inventory: 6, price: 1599 },
    ],
    price: 1599,
    rating: 4.4,
    reviewCount: 78,
    sellerId: "seller5",
    sellerName: "Shoe Paradise",
    visibility: true,
    createdAt: "2024-01-14T00:00:00Z",
    updatedAt: "2024-01-14T00:00:00Z",
  },
]

// Mock carousel slides
export const mockCarouselSlides = [
  {
    id: 1,
    title: "Summer Collection",
    subtitle: "Discover the Latest Trends",
    description: "Light, breezy, and absolutely stunning. Shop our new summer arrivals.",
    image: "/summer-fashion-collection-women.jpg",
    cta: "Shop Now",
    href: "/search?category=dress-skirts",
  },
  {
    id: 2,
    title: "Activewear Sale",
    subtitle: "Up to 30% Off",
    description: "Stay fit and stylish with our premium activewear collection.",
    image: "/activewear-women-yoga.jpg",
    cta: "View Collection",
    href: "/search?category=activewear",
  },
  {
    id: 3,
    title: "New Arrivals",
    subtitle: "Fresh Styles Weekly",
    description: "Be the first to wear our newest designs.",
    image: "/new-fashion-arrivals-women.jpg",
    cta: "Explore",
    href: "/search?sort=newest",
  },
]

// Mock featured shops
export const mockFeaturedShops = [
  {
    id: "seller1",
    name: "Pink Boutique",
    logo: "/pink-boutique-logo.jpg",
    tagline: "Elegant feminine fashion",
    rating: 4.8,
    productCount: 156,
  },
  {
    id: "seller2",
    name: "ActiveWear Hub",
    logo: "/activewear-store-logo.jpg",
    tagline: "Performance meets style",
    rating: 4.9,
    productCount: 89,
  },
  {
    id: "seller3",
    name: "Winter Wardrobe",
    logo: "/winter-clothing-store-logo.jpg",
    tagline: "Stay warm, stay stylish",
    rating: 4.7,
    productCount: 67,
  },
  {
    id: "seller4",
    name: "Intimate Elegance",
    logo: "/lingerie-store-logo.jpg",
    tagline: "Comfort and beauty",
    rating: 4.6,
    productCount: 124,
  },
]

// Mock dashboard data
export const mockDashboardOverview: DashboardOverview = {
  totalSales: 125000,
  totalOrders: 342,
  totalProducts: 56,
  netSales: 112500,
  salesTrend: 12.5,
  ordersTrend: 8.3,
  recentTransactions: [
    {
      id: "t1",
      type: "sale",
      amount: 1299,
      buyerName: "Maria Santos",
      status: "completed",
      createdAt: "2024-01-20T10:30:00Z",
    },
    {
      id: "t2",
      type: "sale",
      amount: 899,
      buyerName: "Ana Cruz",
      status: "completed",
      createdAt: "2024-01-20T09:15:00Z",
    },
    {
      id: "t3",
      type: "refund",
      amount: 799,
      buyerName: "Joy Reyes",
      status: "processed",
      createdAt: "2024-01-19T16:45:00Z",
    },
  ],
  visitors: 1234,
  searchCount: 567,
}

export const mockSalesData: SalesData[] = [
  { date: "2024-01-14", sales: 15000, orders: 42 },
  { date: "2024-01-15", sales: 18500, orders: 51 },
  { date: "2024-01-16", sales: 12000, orders: 35 },
  { date: "2024-01-17", sales: 22000, orders: 58 },
  { date: "2024-01-18", sales: 19500, orders: 48 },
  { date: "2024-01-19", sales: 21000, orders: 55 },
  { date: "2024-01-20", sales: 17000, orders: 53 },
]

export const mockCategoryPerformance: CategoryPerformance[] = [
  { category: "Dress & Skirts", sales: 45000, orders: 120 },
  { category: "Activewear", sales: 32000, orders: 95 },
  { category: "Tops & Blouses", sales: 28000, orders: 85 },
  { category: "Lingerie", sales: 15000, orders: 52 },
  { category: "Accessories", sales: 5000, orders: 30 },
]
